LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE    := lib_spellfix
LOCAL_MODULE_FILENAME    := lib_spellfix
LOCAL_CFLAGS := -O -DNDEBUG -DSQLITE_TEMP_STORE=3 -DSQLITE_DEFAULT_FOREIGN_KEYS=1 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_RTREE -DSQLITE_OS_UNIX
LOCAL_C_INCLUDES := ../../cb/sqlite3
LOCAL_SRC_FILES = ../../../sqlite/ext/misc/spellfix.c

include $(BUILD_SHARED_LIBRARY)

